### ISSUE TITLE
create event

### ISSUE THREAD

**Issue by stevemurphy256** [taco-corp/checkedin_react#25]
get the create event working

**Comment by jonriddick** [comment]
Input from form on event page pushes to mongo database

**Comment by stevemurphy256** [comment]
Jon and I have the data from the input fields to the console.log with the Create Event Button. I got stuck on the axios createEvent function on utils/API.js Kevin was helping us yesterday but he had to go before we got it figured out.

**Comment by zdayar** [comment]
This is done
